"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

[cmd_duration]
disabled = true

[env_var.DESK_NAME]
symbol = "â—² "
format = "in [$symbol($env_value)](blue)"

[aws]
symbol = ""

[kubernetes]
disabled = false
