[misc]
no_retry = true
pre_sudo = true
assume_yes = true
skip_notify = true
disable = ["git_repos"]

# Custom commands
[commands]
"Neovim (lazy.nvim)" = "nvim --headless \"+Lazy! sync\" +qa"
"Neovim (mason.nvim)" = "nvim --headless +MasonUpdate +qa"
"Mise" = "mise upgrade"
